// export const pictureData = {
//     opening: ['https://cdn.redacted.redacted/anolHaKyUuBi.JPG', 'https://cdn.redacted.redacted/qlgfU1dUbmDm.JPG', 'https://cdn.redacted.redacted/DGxLtnta99f3.JPG', 'https://cdn.redacted.redacted/3nvYnE8eOhfe.JPG', 'https://cdn.redacted.redacted/RzNsrw4IKJuc.JPG', 'https://cdn.redacted.redacted/9EQN6gds60T2.JPG', 'https://cdn.redacted.redacted/OZ2hvJnXIE7w.JPG', 'https://cdn.redacted.redacted/HwRhuOErFiwo.JPG', 'https://cdn.redacted.redacted/Wd5wWjxefBU6.JPG', 'https://cdn.redacted.redacted/T9N5mWZOX6tg.JPG', 'https://cdn.redacted.redacted/ptcf10WmB2nE.JPG'],
//     basketball: ['https://cdn.redacted.redacted/19pGXMeVQnus.JPG', 'https://cdn.redacted.redacted/Af2iFTuO61FM.JPG', 'https://cdn.redacted.redacted/u4F5EAJ3EvBm.JPG', 'https://cdn.redacted.redacted/Xe3jV1HFCXDV.JPG', 'https://cdn.redacted.redacted/oTBh98CNIFTk.JPG', 'https://cdn.redacted.redacted/cA3VjaJi5205.JPG', 'https://cdn.redacted.redacted/tsPoXFbbmVah.JPG', 'https://cdn.redacted.redacted/xkFYCRsczZoI.JPG'],
//     futsal: ['https://cdn.redacted.redacted/dYFukZto8FWA.JPG', 'https://cdn.redacted.redacted/x3Wh0ssCayIZ.JPG', 'https://cdn.redacted.redacted/L3Y2CMXbeIF3.JPG', 'https://cdn.redacted.redacted/uMWPb7jJrWRG.JPG', 'https://cdn.redacted.redacted/8hB8IVTMGuIs.JPG', 'https://cdn.redacted.redacted/FxP96bGlvrGn.JPG', 'https://cdn.redacted.redacted/xn0CkBZiQNay.JPG', 'https://cdn.redacted.redacted/KGPSeOGOunix.JPG'],
//     modernDance: ['https://cdn.redacted.redacted/uZFsxBZ724sU.JPG', 'https://cdn.redacted.redacted/yBntBo9NsdAY.JPG', 'https://cdn.redacted.redacted/bfPjXD8orEOl.JPG', 'https://cdn.redacted.redacted/vWLRZ6TvapqH.JPG', 'https://cdn.redacted.redacted/SwCwS6UG4jAW.JPG', 'https://cdn.redacted.redacted/jnAmfzeRYKIk.JPG', 'https://cdn.redacted.redacted/eaSxGPA93dWV.JPG', 'https://cdn.redacted.redacted/v9KflZJwTmrj.JPG', 'https://cdn.redacted.redacted/a4wOB9MF3wLc.JPG', 'https://cdn.redacted.redacted/zVZ95QoDXdOI.JPG'],
//     soloVocal: ['https://cdn.redacted.redacted/30LzdkrLjPRA.png', 'https://cdn.redacted.redacted/LpaStUsO8BrZ.png', 'https://cdn.redacted.redacted/H21nGNEU8Zop.png', 'https://cdn.redacted.redacted/7m9SefzsmEF3.png', 'https://cdn.redacted.redacted/BvnRamZIPcoa.png'],
//     panitia: ["https://cdn.redacted.redacted/Jy2xvMc4yZi7.JPG", "https://cdn.redacted.redacted/zK3g2JYdOt9G.JPG", "https://cdn.redacted.redacted/2j41Mw3NdsX8.JPG", "https://cdn.redacted.redacted/PIr97OuasbIx.JPG", "https://cdn.redacted.redacted/aUIv9aaVDeeP.JPG", "https://cdn.redacted.redacted/xOnoiblJ5WVO.JPG"],
//     closing: ['https://cdn.redacted.redacted/CEKhIBqWFlsI.JPG', 'https://cdn.redacted.redacted/DDUdv98Ka7XK.JPG', 'https://cdn.redacted.redacted/syOo6TxhIOZq.JPG', 'https://cdn.redacted.redacted/17GzdA7HsWGm.JPG', 'https://cdn.redacted.redacted/sHqgAcbykO5R.JPG', 'https://cdn.redacted.redacted/Yptl28z5u7Vq.JPG']
// }

export const pictureData = {
    "opening": ["https://cdn.redacted.redacted/Xel0SFTUtBBj.webp", "https://cdn.redacted.redacted/WzweNPEbfAkx.webp", "https://cdn.redacted.redacted/JJe08oKvymz2.webp", "https://cdn.redacted.redacted/zs72uIjEQbSK.webp", "https://cdn.redacted.redacted/fQc8ozdC406t.webp", "https://cdn.redacted.redacted/uQjOK5e6NKx8.webp", "https://cdn.redacted.redacted/nF5ynrBq9SKc.webp", "https://cdn.redacted.redacted/ZL1nJas0x7yo.webp", "https://cdn.redacted.redacted/4a0ZZFJCvWy2.webp", "https://cdn.redacted.redacted/FEfoH3b5OV9e.webp", "https://cdn.redacted.redacted/9NYQx6ochtra.webp"],
    "basketball": ["https://cdn.redacted.redacted/myfX8cq7CUMh.webp", "https://cdn.redacted.redacted/mRxtbZeEXEMN.webp", "https://cdn.redacted.redacted/8QD5IYNffIDH.webp", "https://cdn.redacted.redacted/YKUhF8cLCieO.webp", "https://cdn.redacted.redacted/IsSM6bcZxuw0.webp", "https://cdn.redacted.redacted/ipPWuKCZOGxf.webp", "https://cdn.redacted.redacted/6fRpLF69a8sZ.webp", "https://cdn.redacted.redacted/0ZV5kBQQ4SKO.webp"],
    "futsal": ["https://cdn.redacted.redacted/F4BjA6IvStWZ.webp", "https://cdn.redacted.redacted/XBist6gv9SIz.webp", "https://cdn.redacted.redacted/GexMFtno4ykw.webp", "https://cdn.redacted.redacted/BSTzmZTMeHiV.webp", "https://cdn.redacted.redacted/jTa1bJwNY3sq.webp", "https://cdn.redacted.redacted/vb6V8safXpkU.webp", "https://cdn.redacted.redacted/ZoosxfVBLLzt.webp", "https://cdn.redacted.redacted/l6hzGePE0Z95.webp"],
    "modernDance": ["https://cdn.redacted.redacted/kxbGMz2uzVdx.webp", "https://cdn.redacted.redacted/c7wq9bemmhy0.webp", "https://cdn.redacted.redacted/6LilkjOORVg7.webp", "https://cdn.redacted.redacted/KvjgLkAfhVsa.webp", "https://cdn.redacted.redacted/zW1XIRW7RRA1.webp", "https://cdn.redacted.redacted/vREIAFiw2L2o.webp", "https://cdn.redacted.redacted/HDnw0eEdOyQX.webp", "https://cdn.redacted.redacted/0E9q1AE0z491.webp", "https://cdn.redacted.redacted/aenFrEdIrvjg.webp", "https://cdn.redacted.redacted/QXlSFWKr98CF.webp"],
    "soloVocal": ["https://cdn.redacted.redacted/x2W60tTT3rJj.webp", "https://cdn.redacted.redacted/tgjLyWwSSTiM.webp", "https://cdn.redacted.redacted/loChdh1lRGBy.webp", "https://cdn.redacted.redacted/T9pELRWjCVWQ.webp", "https://cdn.redacted.redacted/ux8lpm1RgUvY.webp"],
    "panitia": ["https://cdn.redacted.redacted/b0v5BVLmEJur.webp", "https://cdn.redacted.redacted/C4KzkI5t6FC9.webp", "https://cdn.redacted.redacted/npKHHj1hyQn2.webp", "https://cdn.redacted.redacted/lC5CnqrfCncF.webp", "https://cdn.redacted.redacted/Sp02cLuzvkwU.webp", "https://cdn.redacted.redacted/22Ipxhd8ndup.webp"],
    "closing": ["https://cdn.redacted.redacted/emxIeaTv0Gqm.webp", "https://cdn.redacted.redacted/zRDKn5NLSBFF.webp", "https://cdn.redacted.redacted/Q9pNm0SCIoom.webp", "https://cdn.redacted.redacted/H352Vbr5stYB.webp", "https://cdn.redacted.redacted/9eMv7rJtk8wt.webp", "https://cdn.redacted.redacted/O22jfZaF0gFo.webp"]
}